Change AREA ids and add function to remove areas
Epitech-Nantes-Tek3/AREA pull request #115
Opened 2023-02-09 18:14 UTC by JohanCDev

# New feature
The AREAs are now distincts from their id (a uuid generated from the app and sent to the server). It allows us to handle more easily the AREAs while communicating between front and back.

This PR also adds the functionality of removing AREAs, linked to back-end.

# Updated feature

# Bug fixed

Closes #108

2023-02-09 21:53 UTC, STom6 submitted a review, later dismissed
lgtm

2023-02-09 22:49 UTC, osvegn requested changes
Missing documentation

2023-02-09 22:49 UTC, osvegn commented on Server/firebaseFunctions.js
> +    },
missing documentation

2023-02-10 13:04 UTC, CedricCORGE approved these changes, later dismissed
lgtm

2023-02-10 14:38 UTC, osvegn submitted a review, later dismissed

2023-02-10 22:25 UTC, osvegn approved these changes
Look good

2023-02-11 10:34 UTC, 31Nathan approved these changes
LGTM

2023-02-11 10:40 UTC, merged