122 create web profile page
Epitech-Nantes-Tek3/AREA pull request #127
Opened 2023-02-10 22:30 UTC by osvegn

# New feature

# Updated feature

# Bug fixed

2023-02-12 12:12 UTC, 31Nathan requested changes
Documentation mostly

2023-02-12 12:12 UTC, 31Nathan commented on Web/src/AuthPage.js
> +export default function AuthPage(props) {
Missing Props documentation

2023-02-12 12:12 UTC, 31Nathan commented on Web/src/CacheManagement.js
> +// export const cache = () => {
Why do you save this code as commented ?

2023-02-12 12:12 UTC, 31Nathan commented on Web/src/CacheManagement.js
> +export async function getAllCacheData() {
Documentation

2023-02-12 12:12 UTC, 31Nathan commented on Web/src/SettingsPage.js
> +export default function SettingsPage(props) {
Documentation

2023-02-13 14:30 UTC, 31Nathan submitted a review, later dismissed
LGTM

2023-02-14 08:10 UTC, 31Nathan submitted a review, later dismissed
LGTM

2023-02-14 10:09 UTC, CedricCORGE submitted a review, later dismissed
NTR

2023-02-15 07:40 UTC, STom6 submitted a review, later dismissed
lgtm

2023-02-15 10:02 UTC, 31Nathan approved these changes
LGTM

2023-02-15 12:55 UTC, CedricCORGE approved these changes
lgtm

2023-02-15 12:59 UTC, merged