114 Connect to Spotify
Epitech-Nantes-Tek3/AREA pull request #132
Opened 2023-02-14 18:05 UTC by 31Nathan

# New feature
We can now log on to Spotify API with the client ID and secret.
New Actions : 
The user follows an Artist
The user is listening to music
The user is listening to specific music
New Reactions:
The music is paused
Playlist Creation
Shuffle mode

# Updated feature
# Bug fixed

2023-02-14 18:22 UTC, JohanCDev requested changes
Add the actions on the Areas.ts files of web and app

2023-02-14 18:36 UTC, JohanCDev submitted a review, later dismissed
Lgtm

2023-02-15 07:48 UTC, STom6 reviewed
you have to add the description of your service in /Server/Services/description

2023-02-15 07:48 UTC, STom6 commented on Server/Services/spotifyServices.js
> +const spotifyApi = new SpotifyWebApi({
adds documentation

2023-02-15 08:58 UTC, CedricCORGE requested changes
Faire la documentation dans le dossier Services pour ajouter Spotify au about.json

2023-02-15 09:22 UTC, CedricCORGE submitted a review, later dismissed
NTR

2023-02-15 09:28 UTC, osvegn requested changes
One bad documentation, otherwise it seems good

2023-02-15 09:28 UTC, osvegn commented on Server/Services/spotifyServices.js
> + * @module spotify-web-api-node
Module name have to be "spotifyService". Then you can make documentation for constant spotifyWebAPI

2023-02-15 09:44 UTC, osvegn approved these changes
Look good

2023-02-15 09:46 UTC, CedricCORGE approved these changes
NTR

2023-02-15 09:56 UTC, merged