Refactor addArea page
Epitech-Nantes-Tek3/AREA pull request #151
Opened 2023-02-19 19:45 UTC by osvegn

# Updated feature
The area page have been fully changed

![image](https://user-images.githubusercontent.com/72011124/219971354-b57dc05a-2306-46a2-8a60-5fee5d47ad72.png)
![image](https://user-images.githubusercontent.com/72011124/219971367-3f59148e-75f7-4e17-b15b-e5f44d5e52bb.png)
![image](https://user-images.githubusercontent.com/72011124/219971389-8e8471ce-5dcb-4301-8176-e9f948c5813b.png)

2023-02-19 19:48 UTC, STom6 commented on Web/src/AddAreaPage.js
> +    // const [selectedReactionIndex, setSelectedReactionIndex] = useState(0)
variable in commentary perhaps unnecessary?

2023-02-19 20:22 UTC, JohanCDev commented
Make the titles Capitalized as in the app with the property text-transform in the css that is linked

2023-02-21 07:48 UTC, JohanCDev submitted a review, later dismissed
Lgtm

2023-02-21 08:15 UTC, STom6 commented on Web/src/AddAreaPage.js
> +    function goResume() {
doc

2023-02-21 10:08 UTC, JohanCDev requested changes

2023-02-21 10:08 UTC, JohanCDev commented on Web/src/AddAreaPage.js
> +        title: ["Selectionne une action", "Selectionne une réaction", "Choisie le titre de ton area"],
Faute d'orthographe ("Choisie" -> "Choisis")

2023-02-21 15:28 UTC, STom6 submitted a review, later dismissed
lgtm

2023-02-22 08:27 UTC, 31Nathan approved these changes, later dismissed
LGTM

2023-02-22 08:27 UTC, JohanCDev commented
You should see with @STom6 how to change the Areas.ts file, it's missing some critical informations for it to work

2023-02-22 12:53 UTC, 31Nathan approved these changes
LGTM

2023-02-22 12:55 UTC, JohanCDev approved these changes
lgtm

2023-02-22 12:59 UTC, merged