172 Improvement spotifyservice with arealoop
Epitech-Nantes-Tek3/AREA pull request #174
Opened 2023-02-24 06:07 UTC by 31Nathan

# Updated feature
Spotify actions and reactions are now usable for Area Loop

2023-02-24 22:16 UTC, osvegn requested changes
Some changes to do

2023-02-24 22:16 UTC, osvegn commented on Server/Services/spotifyServices.js
> + * @param {*} uid the uid of the spotify user
missing async field

2023-02-24 22:16 UTC, osvegn commented on Server/Services/spotifyServices.js
> + * @param {*} uid the uid of the spotify user
missing async field

2023-02-24 22:16 UTC, osvegn commented on Server/Services/spotifyServices.js
> + * @param {*} uid the uid of the spotify user
missing async field

2023-02-24 22:16 UTC, osvegn commented on Server/Services/spotifyServices.js
> + * @param {*} uid the uid of the spotify user
missing async field

2023-02-24 22:16 UTC, osvegn commented on Server/Services/spotifyServices.js
> +* @param {*} uid the uid of the spotify user
missing async field

2023-02-24 22:16 UTC, osvegn commented on Server/Services/spotifyServices.js
> + * @param {*} uid the uid of the spotify user
missing async field

2023-02-24 22:16 UTC, osvegn commented on Server/Services/spotifyServices.js
>       * @param {*} serverData client credentials of the developper account
missing spotifyToken parameters documentation

2023-02-24 22:16 UTC, osvegn commented on Server/Services/spotifyServices.js
> +     * @param {*} func function chosen by the user
missing async field

2023-02-24 22:16 UTC, osvegn commented on Server/Services/spotifyServices.js
> +                resolve(result)
There isn't better way to do that ?

2023-02-24 22:16 UTC, osvegn commented on Server/app.js
> + * @class class qui contient l'access token & le refresh token, ainsi que l'uid de l'utilisateur pour l'api spotify.
Documentation must be in english

2023-02-25 11:33 UTC, JohanCDev approved these changes
Lgtm

2023-02-25 15:13 UTC, osvegn approved these changes

2023-02-25 16:05 UTC, merged