48 create first test for react
Epitech-Nantes-Tek3/AREA pull request #192
Opened 2023-02-27 15:46 UTC by osvegn

# New feature
- Use playwright to create tests for web part

2023-02-28 13:34 UTC, 31Nathan requested changes
Some things

2023-02-28 13:34 UTC, 31Nathan commented on Web/src/HomePage.js
> +                // overflow: "scroll",
Remove it if it's unused

2023-02-28 13:34 UTC, 31Nathan commented on Web/playwright.config.js
> +
Why commented ?

2023-02-28 13:45 UTC, STom6 approved these changes, later dismissed
lgtm

2023-03-01 14:58 UTC, JohanCDev approved these changes
Ntr

2023-03-02 07:48 UTC, 31Nathan approved these changes
LGTM

2023-03-02 08:52 UTC, STom6 approved these changes
lgtm

2023-03-02 22:01 UTC, merged