update strava documentation to appear in github.io
Epitech-Nantes-Tek3/AREA pull request #228
Opened 2023-03-04 12:18 UTC by STom6

# New feature
Needs to define strava with @module to appear in the doc.

2023-03-04 16:15 UTC, CedricCORGE requested changes

2023-03-04 16:15 UTC, CedricCORGE commented on Server/Services/stravaService.js
> + * @module stravaServie
Service

2023-03-04 20:56 UTC, JohanCDev approved these changes
Lgtm

2023-03-05 11:57 UTC, 31Nathan approved these changes

2023-03-05 13:01 UTC, CedricCORGE approved these changes
lgtm

2023-03-05 13:10 UTC, merged