Terraform
Epitech-Nantes-Tek3/AREA pull request #230
Opened 2023-03-04 18:00 UTC by osvegn

# New feature
Create a bonus!
The server and web app are available over internet. They are deployed on azure using terraform

2023-03-04 19:55 UTC, 31Nathan requested changes

2023-03-04 19:55 UTC, 31Nathan commented on Web/release/client.apk
> +salut
???

2023-03-04 19:55 UTC, 31Nathan commented on defense.md
> +# Defense
Want to push this ?

2023-03-04 20:09 UTC, osvegn commented on Web/release/client.apk
> +salut
a mistake

2023-03-04 20:09 UTC, osvegn commented on defense.md
> +# Defense
a mistake too

2023-03-04 20:33 UTC, JohanCDev approved these changes
Lgtm

2023-03-04 20:55 UTC, JohanCDev approved these changes, later dismissed
Ntr

2023-03-04 23:34 UTC, JohanCDev approved these changes, later dismissed
Lgtm

2023-03-05 11:57 UTC, 31Nathan approved these changes, later dismissed

2023-03-05 13:00 UTC, CedricCORGE approved these changes, later dismissed
lgtm

2023-03-05 13:55 UTC, CedricCORGE approved these changes
lgtm

2023-03-05 16:03 UTC, JohanCDev approved these changes
Lgtm

2023-03-05 16:04 UTC, merged