Add Action : Distance between User (Database) and ISS Station
Epitech-Nantes-Tek3/AREA pull request #55
Opened 2023-01-28 14:04 UTC by 31Nathan

# New feature
Adding a new service for AREA, to check if the ISS Station is near or close to the user.
# Updated feature
Add Got Dependency to Server package.json
# Bug fixed

2023-01-29 08:42 UTC, osvegn requested changes

2023-01-29 08:42 UTC, osvegn commented on Server/Services/ISSStationService.js
> +                    /// https://www.01net.com/actualites/calculer-la-distance-entre-2-points-sur-terre-522697.html#:~:text=La%20formule%20(%C3%A0%20saisir%20par,C3)))*6371.
It seems useless

2023-01-29 08:42 UTC, osvegn commented on Server/Services/ISSStationService.js
> +/// Convert a degree value in radiant
Improve your documentation like this :
```
/**
* @brief
* @param1
* @param2
* ...
* @return
*/

```

2023-01-29 08:42 UTC, osvegn commented on Server/Services/ISSStationService.js
> +    checkISSPosition: function(res, uid) {
Add documentation

2023-01-29 09:31 UTC, STom6 requested changes

2023-01-29 09:31 UTC, STom6 commented on Server/Services/ISSStationService.js
> +        firebaseFunctions.getDataFromFireBase(uid, 'OpenMeteoService')
Rather create an IssStation category in the DB instead of using openMeteoService. The user can use issService without having used openMeteoService

2023-01-30 13:34 UTC, osvegn submitted a review, later dismissed
Look good

2023-01-30 14:42 UTC, JohanCDev commented on Server/Services/ISSStationService.js
> +const heartRadius = 6374
Change this variable name

2023-01-30 14:42 UTC, JohanCDev submitted a review, later dismissed
change var

2023-01-30 14:47 UTC, CedricCORGE approved these changes

2023-01-30 15:10 UTC, osvegn approved these changes
OK

2023-01-30 15:10 UTC, STom6 approved these changes
NTR

2023-01-30 15:22 UTC, merged