62 improvement of the action reaction services
Epitech-Nantes-Tek3/AREA pull request #68
Opened 2023-01-31 21:27 UTC by STom6

# Updated feature
implementation of all triggers for action services:
Lower / upper for iss position.
Good weather / bad weather for the openMeteo service

2023-02-01 22:29 UTC, JohanCDev reviewed
Lgtm

2023-02-02 09:57 UTC, CedricCORGE approved these changes, later dismissed
lgtm

2023-02-02 10:03 UTC, osvegn requested changes
Improve the documentation

2023-02-02 10:03 UTC, osvegn commented on Server/Services/openMeteoService.js
> +    * @brief Check if it is weather is fine or not based on the current date and
> Check if the wheather is fine or not based on the current ...

2023-02-02 10:03 UTC, osvegn commented on Server/Services/openMeteoService.js
> +    * @returns Promise that resolves with location data if successful or rejects with an error if unsuccessful
The sentence may be improved, I don't understand

2023-02-02 10:38 UTC, 31Nathan approved these changes
LGTM

2023-02-02 10:52 UTC, JohanCDev approved these changes
lgtm

2023-02-02 11:13 UTC, osvegn approved these changes
Look good

2023-02-02 11:33 UTC, merged