63 creation of the function that executes the areas
Epitech-Nantes-Tek3/AREA pull request #71
Opened 2023-02-02 10:03 UTC by STom6

# New feature
The area function, which performs reactions if the action trigger is triggered for all user areas contained in the db.
# Updated feature
Improvement of OpenMéteoService, return true or false.
Generalisation of the tweetAct & SendMail functions to use them as pointers to functions.
# Bug fixed

2023-02-05 19:59 UTC, STom6 commented
<img width="604" alt="Screenshot 2023-02-05 at 09 23 52" src="https://user-images.githubusercontent.com/72015208/216841830-489d4682-fc4a-43f7-9c9b-54ff720cd7fe.png">

<img width="1191" alt="Screenshot 2023-02-05 at 09 24 21" src="https://user-images.githubusercontent.com/72015208/216841835-2e6fa714-73b1-4806-951d-b060f79864ff.png">

<img width="604" alt="Screenshot 2023-02-05 at 11 01 27" src="https://user-images.githubusercontent.com/72015208/216841839-3814f6d2-f625-4e8a-848d-e89a9922076f.png">

<img width="512" alt="Screenshot 2023-02-05 at 11 01 41" src="https://user-images.githubusercontent.com/72015208/216841843-087c4fc4-a5c9-424f-acbe-1ce2ae534417.png">

<img width="323" alt="Screenshot 2023-02-05 at 09 24 51" src="https://user-images.githubusercontent.com/72015208/216841847-531dfd9a-7a3e-42e2-82b4-6e1eb5d0575b.png">

<img width="333" alt="Screenshot 2023-02-05 at 09 24 55" src="https://user-images.githubusercontent.com/72015208/216841852-c335cdd7-7579-4c2c-bbfc-e6a8d42c6b50.png">

<img width="289" alt="Screenshot 2023-02-05 at 09 25 00" src="https://user-images.githubusercontent.com/72015208/216841860-d0fac483-d3bb-44c7-9c93-f41d079b161b.png">

<img width="357" alt="Screenshot 2023-02-05 at 09 25 07" src="https://user-images.githubusercontent.com/72015208/216841867-088ae07f-ac5f-4be9-9dd7-f03239db2595.png">

2023-02-06 10:32 UTC, osvegn requested changes

2023-02-06 10:32 UTC, osvegn commented on Server/Services/googleService.js
> +    send_mail: function(subject, mailContent, uid, req, res) {
Update param documentation

2023-02-06 10:40 UTC, JohanCDev approved these changes, later dismissed
ntr

2023-02-06 12:28 UTC, CedricCORGE approved these changes
ntr

2023-02-06 13:08 UTC, osvegn approved these changes
Look good

2023-02-06 13:28 UTC, merged