76 services descriptions
Epitech-Nantes-Tek3/AREA pull request #78
Opened 2023-02-06 08:09 UTC by STom6

# New feature

# Updated feature

# Bug fixed

2023-02-06 12:39 UTC, CedricCORGE commented on Server/Services/description/IssStationService.json
> +            "name": "checkISSPosition",
The name shouldn't be check but compare or something like that

2023-02-06 12:39 UTC, CedricCORGE commented on Server/Services/description/twitterService.json
> +            "name": "Tweet un tweet",
Should be Post a tweet

2023-02-07 15:35 UTC, osvegn commented
Move this pull request as draft pull request if it isn't finished

2023-02-08 08:29 UTC, osvegn requested changes
Grammar

2023-02-08 08:29 UTC, osvegn commented on Server/Services/description/IssStationService.json
> +            "description": "checks the position of the iss in relation to the user-defined position. Compares whether the ISS is within a (user-defined) **gap** around the user. And returns whether t
Capital at beginning

2023-02-08 08:29 UTC, osvegn commented on Server/Services/description/OpenMeteoService.json
> +            "description": "Receive weather data for a location defined by latitude/longitude. Returns with a trigger if the weather is good or bad."
Receives

2023-02-08 08:29 UTC, osvegn commented on Server/Services/description/twitterService.json
> +            "description": "Like the tweet of a hashtag given in parameter"
Likes

2023-02-08 08:29 UTC, osvegn commented on Server/Services/description/twitterService.json
> +            "description": "Retweet the tweet of a hashtag given in parameter"
Retweets

2023-02-08 09:01 UTC, JohanCDev approved these changes, later dismissed
Lgtm

2023-02-08 09:03 UTC, CedricCORGE submitted a review, later dismissed

2023-02-08 09:50 UTC, osvegn requested changes

2023-02-08 09:50 UTC, osvegn commented on Server/Services/description/twitterService.json
> +            "name": "Post a tweet",
Posts

2023-02-08 09:50 UTC, osvegn commented on Server/Services/description/twitterService.json
> +            "description": "Post a tweet with a text given in parameter"
Posts

2023-02-08 09:50 UTC, osvegn commented on Server/Services/description/googleService.json
> +            "name": "Send an email",
Sends

2023-02-08 09:50 UTC, osvegn commented on Server/Services/description/IssStationService.json
> +            "name": "Compare Iss Position With User Position",
Compares

2023-02-08 09:57 UTC, 31Nathan approved these changes, later dismissed
LGTM

2023-02-08 12:07 UTC, osvegn submitted a review, later dismissed

2023-02-08 12:54 UTC, CedricCORGE submitted a review, later dismissed
LGTM

2023-02-08 13:26 UTC, 31Nathan approved these changes

2023-02-08 13:29 UTC, osvegn approved these changes

2023-02-08 13:35 UTC, merged