79 Fix redirection when user isn't connected with facebook/google button
Epitech-Nantes-Tek3/AREA pull request #81
Opened 2023-02-06 12:30 UTC by CedricCORGE

# Bug fixed
Remove the possibility to dodge authentification processus by using google/facebook signin button

Closes #79

2023-02-06 13:31 UTC, STom6 submitted a review, later dismissed
lgtm

2023-02-06 15:20 UTC, JohanCDev reviewed
lgtm

2023-02-06 15:21 UTC, JohanCDev approved these changes, later dismissed

2023-02-06 23:41 UTC, osvegn requested changes
Some questions about code and comments

2023-02-06 23:41 UTC, osvegn commented on Application/src/Screens/ConnexionScreen.tsx
> +        NavigatorPush("HomeScreen", "mainStack", options, props)*/
Why is it kept as comment ?

2023-02-06 23:41 UTC, osvegn commented on Application/src/Screens/SignInScreen.tsx
> +        NavigatorPush("HomeScreen", "mainStack", options, props)*/
Why is it kept as comment ?

2023-02-06 23:41 UTC, osvegn commented on Application/src/Screens/SignInScreen.tsx
> +        console.log(data.accessToken)
Useful to log an access token ?

2023-02-07 09:41 UTC, 31Nathan approved these changes
LGTM

2023-02-07 12:58 UTC, osvegn approved these changes
Look good

2023-02-07 13:15 UTC, merged